import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Siyanda',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
      imgUrl:
        'https://res.cloudinary.com/dxpeznnto/image/upload/v1670804266/samples/people/kitchen-bar.jpg',
    },
    {
      name: 'Stilo',
      email: 'useer@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
      imgUrl:
        'https://res.cloudinary.com/dxpeznnto/image/upload/v1670804269/samples/people/smiling-man.jpg',
    },
  ],

  team: [
    {
      name: 'Marcus Doe',
      role: 'Manager',
      imgUrl: '/images/marcus.png',
    },
    {
      name: 'Morgan Row',
      role: 'Senior Chef',
      imgUrl: '/images/morgan.png',
    },
    {
      name: 'Jaden Bun',
      role: 'Supervisor',
      imgUrl: '/images/jaden.png',
    },
    {
      name: 'Aarna Signh',
      role: 'Marketing Director',
      imgUrl: '/images/aarna.png',
    },
    {
      name: 'Anthony Johnson',
      role: 'Delivery Manager',
      imgUrl: '/images/anthony.png',
    },
  ],

  products: [
    {
      name: 'Bacon & Cheese',
      slug: 'Bacon-&-Cheese',
      type: 'burger',
      imgUrl: '/images/bacon_and_cheese_burger.png',
      price: 45,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 14,
    },
    {
      name: 'Bacon & Purple Onion',
      slug: 'Bacon-&-Purple-Onion',
      type: 'pizza',
      imgUrl: '/images/bacon_and_purple_onion.png',
      price: 64,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 14,
    },
    {
      name: 'Bacon & Mushroom',
      slug: 'Bacon-&-Mushroom',
      type: 'burger',
      imgUrl: '/images/beef_and_mushroom.png',
      price: 55,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 3.5,
      numRatings: 18,
    },
    {
      name: 'Beef Cotlet',
      slug: 'Beef-Cotlet',
      type: 'burger',
      imgUrl: '/images/beef_cotlet.png',
      price: 42,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 3.5,
      numRatings: 11,
    },
    {
      name: 'Bell Pepper & Cheese',
      slug: 'Bell-Pepper-&-Cheese',
      type: 'pizza',
      imgUrl: '/images/bell_pepper_and_cheese.png',
      price: 84,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      name: 'Broadleaf Red Wine',
      slug: 'Broadleaf-Red-Wine',
      type: 'drink',
      imgUrl: '/images/broadleaf_red_wine.png',
      price: 68,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 26,
    },
    {
      name: 'Buns loaf bread',
      slug: 'Buns-loaf-bread',
      type: 'bread',
      imgUrl: '/images/buns-loaf-bread-stone-surface.png',
      price: 32,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 2.5,
      numRatings: 8,
    },
    {
      name: 'Cheese Burger',
      slug: 'Cheese-Burger',
      type: 'burger',
      imgUrl: '/images/cheese.png',
      price: 38,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 3.0,
      numRatings: 8,
    },
    {
      name: 'Cheesy Tomato',
      slug: 'Cheesy-Tomato',
      type: 'pizza',
      imgUrl: '/images/cheesey_tomato.png',
      price: 78,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.0,
      numRatings: 22,
    },
    {
      name: 'Chicken & Lettuce',
      slug: 'Chicken-&-Lettuce',
      type: 'burger',
      imgUrl: '/images/chicken_and_lettuce.png',
      price: 58,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      name: 'Chicken & Melted Cheese',
      slug: 'Chicken-&-Melted-Cheese',
      type: 'burger',
      imgUrl: '/images/chicken_and_melted_cheese.png',
      price: 62,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      name: 'Chicken & Tomato Sauce',
      slug: 'Chicken-&-Tomato-Sauce',
      type: 'burger',
      imgUrl: '/images/chicken_and_tomato_sauce.png',
      price: 45,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 3.5,
      numRatings: 22,
    },
    {
      name: 'Chicken Strips',
      slug: 'Chicken-Strips',
      type: 'salad',
      imgUrl: '/images/chicken_strips.png',
      price: 65,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      name: 'Chocolate & Cherry',
      slug: 'Chocolate-&-Cherry',
      type: 'dessert',
      imgUrl: '/images/chocolate_and_cherry.png',
      price: 62,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 3.5,
      numRatings: 22,
    },
    {
      name: 'Chocolate Bread & Blueberry',
      slug: 'Chocolate-Bread-&-Blueberry',
      type: 'dessert',
      imgUrl: '/images/chocolate_bread_and_blueberry.png',
      price: 55,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 3.5,
      numRatings: 22,
    },
    {
      name: 'Chocolate Tart',
      slug: 'Chocolate-Tart',
      type: 'dessert',
      imgUrl: '/images/chocolate_tart.png',
      price: 54,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      name: 'Coke Small',
      slug: 'Coke-Small',
      type: 'drink',
      imgUrl: '/images/coke.png',
      price: 16,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 3.5,
      numRatings: 22,
    },
    {
      name: 'Coke Can',
      slug: 'Coke-Can',
      type: 'drink',
      imgUrl: '/images/coke_can.png',
      price: 15,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 3.5,
      numRatings: 22,
    },
    {
      name: 'Crispy Baked Loaf',
      slug: 'Crispy-Baked-Loaf',
      type: 'bread',
      imgUrl: '/images/crispy_baked_loaf.png',
      price: 22,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 3.5,
      numRatings: 22,
    },
    {
      name: 'Crispy Made Loaf',
      slug: 'Crispy-Made-Loaf',
      type: 'bread',
      imgUrl: '/images/crispy_made_loaf.png',
      price: 32,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 3.5,
      numRatings: 22,
    },
    {
      name: 'Crispy Olives & Sausage',
      slug: 'Crispy-Olives-&-Sausage',
      type: 'pizza',
      imgUrl: '/images/crispy_olives_and_sausage.png',
      price: 82,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      name: 'Dark Chocolate Bun',
      slug: 'Dark-Chocolate-Bun',
      type: 'bread',
      imgUrl: '/images/dark_chocolate_bun.png',
      price: 22,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 3.5,
      numRatings: 22,
    },
    {
      name: 'Dark Chocolate Cupcake',
      slug: 'Dark-Chocolate-Cupcake',
      type: 'dessert',
      imgUrl: '/images/dark_chocolate_cupcake.png',
      price: 22,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      name: 'Dark Chocolate Milkshake',
      slug: 'Dark-Chocolate-Milkshake',
      type: 'drink',
      imgUrl: '/images/dark_chocolate_milkshake.png',
      price: 45,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 3.5,
      numRatings: 22,
    },
    {
      name: 'Double Chicken Sauced',
      slug: 'Double-Chicken-Sauced',
      type: 'burger',
      imgUrl: '/images/double_chicken_sauced.png',
      price: 60,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      name: 'Freshly Baked Bun',
      slug: 'Freshly-Baked-Bun',
      type: 'bread',
      imgUrl: '/images/freshly_baked_bun.png',
      price: 55,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 3.5,
      numRatings: 22,
    },
    {
      name: 'Full Vegetables',
      slug: 'Full-Vegetables',
      type: 'salad',
      imgUrl: '/images/full_vegetables.png',
      price: 120,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      name: 'Greens & White Cheese',
      slug: 'Greens-&-White-Cheese',
      type: 'salad',
      imgUrl: '/images/green_and_white_cheese.png',
      price: 140,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      name: 'Greens & Eggs',
      slug: 'Greens-&-Eggs',
      type: 'salad',
      imgUrl: '/images/greens_and_eggs.png',
      price: 160,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      name: 'Maghitarama',
      slug: 'Maghitarama',
      type: 'pizza',
      imgUrl: '/images/maghitarama.png',
      price: 95,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      name: 'Melted Cheese & Bacon',
      slug: 'Melted-Cheese-&-Bacon',
      type: 'pizza',
      imgUrl: '/images/melted_cheese_and_bacon.png',
      price: 110,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      name: 'Mushroom & Melted Cheese',
      slug: 'Mushroom-&-Melted-Cheese',
      type: 'pizza',
      imgUrl: '/images/mushroom_and_melted_cheese.png',
      price: 80,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 3.5,
      numRatings: 22,
    },
    {
      name: 'Olives & Melted White Cheese',
      slug: 'Olives-&-Melted-White-Cheese',
      type: 'pizza',
      imgUrl: '/images/olives_and_melted_whitecheese.png',
      price: 79,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      name: 'Olives & Pepper',
      slug: 'Olives-&-Pepper',
      type: 'pizza',
      imgUrl: '/images/olives_and_pepper.png',
      price: 105,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      name: 'Oreo & Chocolate Milkshake',
      slug: 'Oreo-&-Chocolate-Milkshake',
      type: 'drink',
      imgUrl: '/images/oreo_and_chocolate_milkshake.png',
      price: 45,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      name: 'Oreo & Strawberry Milkshake',
      slug: 'Oreo-&-Strawberry-Milkshake',
      type: 'drink',
      imgUrl: '/images/oreo_and_strawberry_milkshake.png',
      price: 45,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      name: 'Oreo Milkshake',
      slug: 'Oreo-Milkshake',
      type: 'drink',
      imgUrl: '/images/oreo_milkshake.png',
      price: 35,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      name: 'Paros Red Wine',
      slug: 'Paros-Red-Wine',
      type: 'drink',
      imgUrl: '/images/paros_red_wine.png',
      price: 68,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      name: 'Pastry',
      slug: 'Pastry',
      type: 'bread',
      imgUrl: '/images/pastry.png',
      price: 45,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      name: 'Red Bacon',
      slug: 'Red-Bacon',
      type: 'pizza',
      imgUrl: '/images/red_bacon.png',
      price: 115,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      name: 'Shrimp Dish',
      slug: 'Shrimp-Dish',
      type: 'salad',
      imgUrl: '/images/shrimp_dish.png',
      price: 115,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      name: 'Soft Baked Bun',
      slug: 'Soft-Baked-Bun',
      type: 'bread',
      imgUrl: '/images/soft_baked_bun.png',
      price: 24,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      name: 'Strawberry Cupcake',
      slug: 'Strawberry-Cupcake',
      type: 'dessert',
      imgUrl: '/images/strawberry_cupcake.png',
      price: 32,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      name: 'Strawberry Folds',
      slug: 'Strawberry-Folds',
      type: 'dessert',
      imgUrl: '/images/strawberry_folds.png',
      price: 45,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      name: 'Tomato & Wors',
      slug: 'Tomato-&-Wors',
      type: 'salad',
      imgUrl: '/images/tomato_and_wors.png',
      price: 115,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      name: 'Tomato & Yellow Pepper',
      slug: 'Tomato-&-Yellow-Pepper',
      type: 'salad',
      imgUrl: '/images/tomato_and_yellow_pepper.png',
      price: 125,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      name: 'Tomato Nectarine',
      slug: 'Tomato-Nectarine',
      type: 'salad',
      imgUrl: '/images/tomato_nectarine.png',
      price: 90,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      name: 'Waffle & Blackberry',
      slug: 'Waffle-&-Blackberry',
      type: 'dessert',
      imgUrl: '/images/waffle_and_blackberry.png',
      price: 65,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      name: 'Waffle & Strawberry',
      slug: 'Waffle-&-Strawberry',
      type: 'dessert',
      imgUrl: '/images/waffle_and_strawberry.png',
      price: 65,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      name: 'Waffle & Vanilla Cream',
      slug: 'Waffle-&-Vanilla-Cream',
      type: 'dessert',
      imgUrl: '/images/waffle_and_vanilla_cream.png',
      price: 45,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      name: 'Zinger Patty',
      slug: 'Zinger-Patty',
      type: 'burger',
      imgUrl: '/images/zinger_patty.png',
      price: 55,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
  ],

  menus: [
    {
      icon: 'ion:fast-food',
      title: 'All',
      slug: 'all',
    },
    {
      icon: 'fa6-solid:burger',
      title: 'Burger',
      slug: 'burger',
    },
    {
      icon: 'fluent:food-pizza-24-filled',
      title: 'Pizza',
      slug: 'pizza',
    },
    {
      icon: 'icon-park-solid:bread',
      title: 'Bread',
      slug: 'bread',
    },
    {
      icon: 'mingcute:drink-fill',
      title: 'Drink',
      slug: 'drink',
    },
    {
      icon: 'fluent:bowl-salad-24-filled',
      title: 'Salad',
      slug: 'salad',
    },
    {
      icon: 'ion:ice-cream',
      title: 'Dessert',
      slug: 'dessert',
    },
  ],

  recommendations: [
    {
      message:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu turpis molestie, dictum est a, mattis tellus. Sed dignissim, metus nec fringilla accumsan, risus sem sollicitudin lacus, ut interdum tellus elit sed risus. Maecenas eget condimentum velit, sit amet feugiat lectus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.',
      name: 'Jane Doe',
      imgUrl: '/images/avatar1.png',
    },
    {
      message:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu turpis molestie, dictum est a, mattis tellus. Sed dignissim, metus nec fringilla accumsan, risus sem sollicitudin lacus, ut interdum tellus elit sed risus. Maecenas eget condimentum velit, sit amet feugiat lectus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.',
      name: 'Jane Doe',
      imgUrl: '/images/avatar1.png',
    },
    {
      message:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu turpis molestie, dictum est a, mattis tellus. Sed dignissim, metus nec fringilla accumsan, risus sem sollicitudin lacus, ut interdum tellus elit sed risus. Maecenas eget condimentum velit, sit amet feugiat lectus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.',
      name: 'Jane Doe',
      imgUrl: '/images/avatar1.png',
    },
  ],
};

export default data;
