const data = {
  products: [
    {
      id: 1,
      name: 'Bacon & Cheese',
      type: 'burger',
      imgUrl: '/images/bacon_and_cheese_burger.png',
      price: 45,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 14,
    },
    {
      id: 2,
      name: 'Bacon & Purple Onion',
      type: 'pizza',
      imgUrl: '/images/bacon_and_purple_onion.png',
      price: 64,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 14,
    },
    {
      id: 3,
      name: 'Bacon & Mushroom',
      type: 'burger',
      imgUrl: '/images/beef_and_mushroom.png',
      price: 55,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 3.5,
      numRatings: 18,
    },
    {
      id: 4,
      name: 'Beef Cotlet',
      type: 'burger',
      imgUrl: '/images/beef_cotlet.png',
      price: 42,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 3.5,
      numRatings: 11,
    },
    {
      id: 5,
      name: 'Bell Pepper & Cheese',
      type: 'pizza',
      imgUrl: '/images/bell_pepper_and_cheese.png',
      price: 84,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      id: 6,
      name: 'Broadleaf Red Wine',
      type: 'drink',
      imgUrl: '/images/broadleaf_red_wine.png',
      price: 68,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 26,
    },
    {
      id: 7,
      name: 'Buns loaf bread',
      type: 'bread',
      imgUrl: '/images/buns-loaf-bread-stone-surface.png',
      price: 32,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 2.5,
      numRatings: 8,
    },
    {
      id: 8,
      name: 'Cheese Burger',
      type: 'burger',
      imgUrl: '/images/cheese.png',
      price: 38,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 3.0,
      numRatings: 8,
    },
    {
      id: 9,
      name: 'Cheesy Tomato',
      type: 'pizza',
      imgUrl: '/images/cheesey_tomato.png',
      price: 78,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.0,
      numRatings: 22,
    },
    {
      id: 10,
      name: 'Chicken & Lettuce',
      type: 'burger',
      imgUrl: '/images/chicken_and_lettuce.png',
      price: 58,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      id: 11,
      name: 'Chicken & Melted Cheese',
      type: 'burger',
      imgUrl: '/images/chicken_and_melted_cheese.png',
      price: 62,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      id: 12,
      name: 'Chicken & Tomato Sauce',
      type: 'burger',
      imgUrl: '/images/chicken_and_tomato_sauce.png',
      price: 45,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 3.5,
      numRatings: 22,
    },
    {
      id: 13,
      name: 'Chicken Strips',
      type: 'salad',
      imgUrl: '/images/chicken_strips.png',
      price: 65,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      id: 14,
      name: 'Chocolate & Cherry',
      type: 'dessert',
      imgUrl: '/images/chocolate_and_cherry.png',
      price: 62,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 3.5,
      numRatings: 22,
    },
    {
      id: 15,
      name: 'Chocolate Bread & Blueberry',
      type: 'dessert',
      imgUrl: '/images/chocolate_bread_and_blueberry.png',
      price: 55,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 3.5,
      numRatings: 22,
    },
    {
      id: 16,
      name: 'Chocolate Tart',
      type: 'dessert',
      imgUrl: '/images/chocolate_tart.png',
      price: 54,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      id: 17,
      name: 'Coke Small',
      type: 'drink',
      imgUrl: '/images/coke.png',
      price: 16,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 3.5,
      numRatings: 22,
    },
    {
      id: 18,
      name: 'Coke Can',
      type: 'drink',
      imgUrl: '/images/coke_can.png',
      price: 15,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 3.5,
      numRatings: 22,
    },
    {
      id: 19,
      name: 'Crispy Baked Loaf',
      type: 'bread',
      imgUrl: '/images/crispy_baked_loaf.png',
      price: 22,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 3.5,
      numRatings: 22,
    },
    {
      id: 20,
      name: 'Crispy Made Loaf',
      type: 'bread',
      imgUrl: '/images/crispy_made_loaf.png',
      price: 32,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 3.5,
      numRatings: 22,
    },
    {
      id: 21,
      name: 'Crispy Olives & Sausage',
      type: 'pizza',
      imgUrl: '/images/crispy_olives_and_sausage.png',
      price: 82,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      id: 22,
      name: 'Dark Chocolate Bun',
      type: 'bread',
      imgUrl: '/images/dark_chocolate_bun.png',
      price: 22,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 3.5,
      numRatings: 22,
    },
    {
      id: 23,
      name: 'Dark Chocolate Cupcake',
      type: 'dessert',
      imgUrl: '/images/dark_chocolate_cupcake.png',
      price: 22,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      id: 24,
      name: 'Dark Chocolate Milkshake',
      type: 'drink',
      imgUrl: '/images/dark_chocolate_milkshake.png',
      price: 45,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 3.5,
      numRatings: 22,
    },
    {
      id: 25,
      name: 'Double Chicken Sauced',
      type: 'burger',
      imgUrl: '/images/double_chicken_sauced.png',
      price: 60,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      id: 26,
      name: 'Freshly Baked Bun',
      type: 'bread',
      imgUrl: '/images/freshly_baked_bun.png',
      price: 55,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 3.5,
      numRatings: 22,
    },
    {
      id: 27,
      name: 'Full Vegetables',
      type: 'salad',
      imgUrl: '/images/full_vegetables.png',
      price: 120,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      id: 28,
      name: 'Greens & White Cheese',
      type: 'salad',
      imgUrl: '/images/green_and_white_cheese.png',
      price: 140,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      id: 29,
      name: 'Greens & Eggs',
      type: 'salad',
      imgUrl: '/images/greens_and_eggs.png',
      price: 160,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      id: 30,
      name: 'Maghitarama',
      type: 'pizza',
      imgUrl: '/images/maghitarama.png',
      price: 95,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      id: 31,
      name: 'Melted Cheese & Bacon',
      type: 'pizza',
      imgUrl: '/images/melted_cheese_and_bacon.png',
      price: 110,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      id: 32,
      name: 'Mushroom & Melted Cheese',
      type: 'pizza',
      imgUrl: '/images/mushroom_and_melted_cheese.png',
      price: 80,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 3.5,
      numRatings: 22,
    },
    {
      id: 33,
      name: 'Olives & Melted White Cheese',
      type: 'pizza',
      imgUrl: '/images/olives_and_melted_whitecheese.png',
      price: 79,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      id: 34,
      name: 'Olives & Pepper',
      type: 'pizza',
      imgUrl: '/images/olives_and_pepper.png',
      price: 105,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      id: 35,
      name: 'Oero & Chocolate Milkshake',
      type: 'drink',
      imgUrl: '/images/oreo_and_chocolate_milkshake.png',
      price: 45,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      id: 36,
      name: 'Oero & Strawberry Milkshake',
      type: 'drink',
      imgUrl: '/images/oreo_and_strawberry_milkshake.png',
      price: 45,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      id: 37,
      name: 'Oero Milkshake',
      type: 'drink',
      imgUrl: '/images/oreo_milkshake.png',
      price: 35,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      id: 38,
      name: 'Paros Red Wine',
      type: 'drink',
      imgUrl: '/images/paros_red_wine.png',
      price: 68,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      id: 39,
      name: 'Pastry',
      type: 'bread',
      imgUrl: '/images/pastry.png',
      price: 45,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      id: 40,
      name: 'Red Bacon',
      type: 'pizza',
      imgUrl: '/images/red_bacon.png',
      price: 115,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      id: 41,
      name: 'Shrimp Dish',
      type: 'salad',
      imgUrl: '/images/shrimp_dish.png',
      price: 115,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      id: 42,
      name: 'Soft Baked Bun',
      type: 'bread',
      imgUrl: '/images/soft_baked_bun.png',
      price: 24,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      id: 43,
      name: 'Strawberry Cupcake',
      type: 'dessert',
      imgUrl: '/images/strawberry_cupcake.png',
      price: 32,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      id: 44,
      name: 'Strawberry Folds',
      type: 'dessert',
      imgUrl: '/images/strawberry_folds.png',
      price: 45,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      id: 45,
      name: 'Tomato & Wors',
      type: 'salad',
      imgUrl: '/images/tomato_and_wors.png',
      price: 115,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      id: 46,
      name: 'Tomato & Yellow Pepper',
      type: 'salad',
      imgUrl: '/images/tomato_and_yellow_pepper.png',
      price: 125,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      id: 47,
      name: 'Tomato Nectarine',
      type: 'salad',
      imgUrl: '/images/tomato_nectarine.png',
      price: 90,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      id: 48,
      name: 'Waffle & Blackberry',
      type: 'dessert',
      imgUrl: '/images/waffle_and_blackberry.png',
      price: 65,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      id: 49,
      name: 'Waffle & Strawberry',
      type: 'dessert',
      imgUrl: '/images/waffle_and_strawberry.png',
      price: 65,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      id: 50,
      name: 'Waffle & Vanilla Cream',
      type: 'dessert',
      imgUrl: '/images/waffle_and_vanilla_cream.png',
      price: 45,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
    {
      id: 51,
      name: 'Zinger Patty',
      type: 'burger',
      imgUrl: '/images/zinger_patty.png',
      price: 55,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum luctus orci lacus, sit amet blandit sem congue et.',
      inStock: 10,
      rating: 4.5,
      numRatings: 22,
    },
  ],

  menus: [
    {
      icon: 'ion:fast-food',
      title: 'All',
      slug: 'all',
    },
    {
      icon: 'fa6-solid:burger',
      title: 'Burger',
      slug: 'burger',
    },
    {
      icon: 'fluent:food-pizza-24-filled',
      title: 'Pizza',
      slug: 'pizza',
    },
    {
      icon: 'icon-park-solid:bread',
      title: 'Bread',
      slug: 'bread',
    },
    {
      icon: 'mingcute:drink-fill',
      title: 'Drink',
      slug: 'drink',
    },
    {
      icon: 'fluent:bowl-salad-24-filled',
      title: 'Salad',
      slug: 'salad',
    },
    {
      icon: 'ion:ice-cream',
      title: 'Dessert',
      slug: 'dessert',
    },
  ],
};

export default data;
